#!/usr/bin/env node
/**
 * @holeauth/rbac-yaml — build-time codegen CLI.
 *
 * Reads a YAML RBAC definition and emits a TypeScript module that exports a
 * fully-resolved snapshot. Consumers can then import the generated module
 * (instead of calling `loadRbacYaml` at runtime) so the bundle has zero
 * dependency on `node:fs` — useful for Next.js Edge runtime, Cloudflare
 * Workers, and other contexts where filesystem access is unavailable.
 *
 * Usage:
 *
 * ```sh
 * holeauth-rbac-codegen --input ./holeauth.rbac.yml --output ./lib/rbac.generated.ts
 * ```
 *
 * Then at runtime:
 *
 * ```ts
 * import { snapshot } from './lib/rbac.generated';
 * import { rbacFromSnapshot } from '@holeauth/rbac-yaml';
 *
 * const plugin = rbacFromSnapshot(snapshot, { adapter: rbacAdapter });
 * ```
 */
import { readFileSync, writeFileSync, mkdirSync } from 'node:fs';
import { dirname, resolve } from 'node:path';
import { parse as parseYaml } from 'yaml';
import { validateRbacDefinition, type RbacConfigSnapshot } from './index.js';

interface CliOptions {
  input: string;
  output: string;
  exportName: string;
}

function parseArgs(argv: readonly string[]): CliOptions {
  let input: string | undefined;
  let output: string | undefined;
  let exportName = 'snapshot';

  for (let i = 0; i < argv.length; i++) {
    const a = argv[i];
    const next = argv[i + 1];
    if ((a === '--input' || a === '-i') && next) {
      input = next;
      i++;
    } else if ((a === '--output' || a === '-o') && next) {
      output = next;
      i++;
    } else if (a === '--export' && next) {
      exportName = next;
      i++;
    } else if (a === '--help' || a === '-h') {
      printHelp();
      process.exit(0);
    } else {
      // eslint-disable-next-line no-console
      console.error(`unknown argument: ${a}`);
      printHelp();
      process.exit(2);
    }
  }

  if (!input || !output) {
    printHelp();
    process.exit(2);
  }

  return { input, output, exportName };
}

function printHelp(): void {
  // eslint-disable-next-line no-console
  console.error(
    [
      'holeauth-rbac-codegen — generate a typed RBAC snapshot from a YAML file',
      '',
      'Usage:',
      '  holeauth-rbac-codegen --input <path.yml> --output <path.ts> [--export <name>]',
      '',
      'Options:',
      '  -i, --input <path>    YAML source file (required)',
      '  -o, --output <path>   TypeScript output file (required)',
      '      --export <name>   Named export for the snapshot (default: "snapshot")',
      '  -h, --help            Show this help',
    ].join('\n'),
  );
}

function emit(snapshot: RbacConfigSnapshot, exportName: string, sourcePath: string): string {
  const lines: string[] = [];
  lines.push(`// AUTO-GENERATED by @holeauth/rbac-yaml — DO NOT EDIT.`);
  lines.push(`// Source: ${sourcePath}`);
  lines.push(`// Re-run holeauth-rbac-codegen to update.`);
  lines.push('');
  lines.push(`export const ${exportName} = ${JSON.stringify(snapshot, null, 2)} as const;`);
  lines.push('');
  lines.push(`export const groups = ${exportName}.groups;`);
  lines.push(`export const defaultGroupId = ${exportName}.defaultGroupId;`);
  lines.push('');
  return lines.join('\n');
}

function main(): void {
  const opts = parseArgs(process.argv.slice(2));
  const inputAbs = resolve(opts.input);
  const outputAbs = resolve(opts.output);

  const text = readFileSync(inputAbs, 'utf8');
  const parsed = parseYaml(text);
  const snapshot = validateRbacDefinition(parsed);

  const code = emit(snapshot, opts.exportName, opts.input);
  mkdirSync(dirname(outputAbs), { recursive: true });
  writeFileSync(outputAbs, code, 'utf8');

  // eslint-disable-next-line no-console
  console.log(
    `[rbac-yaml] wrote ${outputAbs} (${snapshot.groups.length} groups, default="${snapshot.defaultGroupId}")`,
  );
}

main();
